#!/bin/bash

make all test test-rss &&
    cd test &&
    ./test && ./test-rss && ./run-uitests-headless.sh

cd -
mkdir -p result
cp -t result test/*.log test/RESULT*.xml
export BUILD_ARTEFACTS=result
